/**
 * AI Text Detection Utilities
 * Converts Python AI detection code to JavaScript
 */

// Helper function to calculate standard deviation
function calculateStandardDeviation(values) {
  if (values.length === 0) return 0;

  const mean = values.reduce((sum, val) => sum + val, 0) / values.length;
  const squaredDiffs = values.map((val) => Math.pow(val - mean, 2));
  const avgSquaredDiff = squaredDiffs.reduce((sum, val) => sum + val, 0) / values.length;

  return Math.sqrt(avgSquaredDiff);
}

// Helper function to count occurrences of a pattern in text
function countMatches(text, pattern) {
  const matches = text.match(pattern);
  return matches ? matches.length : 0;
}

// Helper function to create n-grams
function createNGrams(words, n) {
  const ngrams = [];
  for (let i = 0; i <= words.length - n; i++) {
    ngrams.push(words.slice(i, i + n).join(' '));
  }
  return ngrams;
}

// Helper function to count frequencies
function countFrequencies(items) {
  const counts = {};
  items.forEach((item) => {
    counts[item] = (counts[item] || 0) + 1;
  });
  return counts;
}

/**
 * Extract AI detection signals from text
 * @param {string} text - The text to analyze
 * @returns {Object} Object containing various AI detection metrics
 */
function extractAiSignals(text) {
  // Detect unicode / formatting artifacts
  const unicodePatterns = {
    em_dashes: countMatches(text, /—/g),
    smart_quotes: countMatches(text, /[""]/g),
    zero_width: countMatches(text, /\u200B/g),
    nbsp: countMatches(text, /\u00A0/g),
  };

  // Burstiness: variance of sentence lengths
  const sentences = text.split(/[.!?]/).filter((s) => s.trim());
  const sentenceLengths = sentences.map((s) => s.trim().split(/\s+/).length);
  const burstiness = calculateStandardDeviation(sentenceLengths);

  // N-gram repetition (3-grams)
  const words = text.toLowerCase().match(/\w+/g) || [];
  const trigrams = createNGrams(words, 3);
  const trigramCounts = countFrequencies(trigrams);
  const highRepeats = Object.values(trigramCounts).filter((count) => count > 1).length;

  // Cliché patterns - comprehensive list
  const clichePhrases = [
    'Indeed',
    'Furthermore',
    'However',
    'Notably',
    'Therefore',
    'Additionally',
    'In terms of',
    'Significantly',
    'It is worth noting',
    'In conclusion',
    'Consequently',
    'Thus',
    'Moreover',
    'Subsequently',
    'Accordingly',
    'Unlock the potential of',
    'Unleash the power of',
    'Delve into the world of',
    'Pave the way for',
    'At the forefront of',
    'Harness the power of',
    'Embark on a journey',
    'Push the boundaries of',
    'A gateway to',
    'Bridging the gap between',
    'Spearhead the initiative',
    'Capitalize on the opportunities',
    'Navigate the complexities',
    'Lay the groundwork for',
    'Foster a culture of',
    "It's important to note that",
    "It's worth mentioning that",
    "Let's delve in",
    "Let's uncover",
    'Due to the fact that',
    'It is important to know',
    'Can vary depending on what',
    'You may want to check',
    'It is generally considered impolite',
    'As a matter of fact',
    'In light of the fact that',
    'It is crucial to understand',
    'Given the fact that',
    'It is essential to consider',
    'Bearing in mind that',
    'Vibrant',
    'Tapestry',
    'Seamless',
    'Smooth',
    'Easy',
    'Effortless',
    'Comprehensive',
    'Intricate',
    'Pivotal',
    'Important to consider',
    'Based on the information provided',
    'Remember that',
    'Navigating the landscape',
    'Navigating the complexities of',
    'Delving into the intricacies of',
    'A testament to',
    'Exploring new frontiers',
    'Exploring this avenue',
    'Foster the development',
    'Future might see us placing',
    'Groundbreaking way',
    'Have come a long way in recent years',
    'Hold promise',
    'Implications are profound',
    'Improved efficiency in countless ways',
    'In the fast-paced world',
    'It discovered an intriguing approach',
    'It remains to be seen',
    'It serves as a stepping stone towards the realization',
    'Latest breakthrough signifies',
    'Latest offering',
    "Let's delve into the exciting details",
    'Main message to take away',
    'Make informed decisions',
    'Mark a significant step forward',
    'Mind-boggling figure',
    'More robust evaluation',
    'Navigate the landscape',
    'One step closer',
    'One thing is clear',
    'Opens up exciting possibilities',
    'Paving the way for enhanced performance',
    'Possibilities are endless',
    'Potentially revolutionizing the way',
    'Raise fairness concerns',
    'Raise intriguing questions',
    'Remarkable abilities',
    'Remarkable breakthrough',
    'Remarkable proficiency',
    'Remarkable success',
    'Remarkable tool',
    'Represent a major milestone',
    'Represents a significant milestone in the field',
    'Risks of drawing unsupported conclusions',
    'Seeking trustworthiness',
    'Significant step forward',
    'Significant strides',
    'The necessity of clear understanding',
    'There is still room for improvement',
    'Uncover hidden trends',
    'Understanding of the capabilities',
    'Unleashing the potential',
    'Unlocking the power',
    'We can improve understanding and decision-making',
    'Welcome your thoughts',
    'What sets this apart',
    'With the introduction',
    'Designed to enhance',
    'It is advisable',
    'When it comes to',
    'You could consider',
    "In today's digital age",
    'To put it simply',
    'Dive into',
    'Excels',
    'Imagine',
    'Enhance',
    'Emphasize',
    'Revolutionize',
    'Foster',
    'Whispering',
    'Reverberate',
    'Promptly',
    'Meticulous',
    'Complexities',
    'Realm',
    'Understanding',
    'Everchanging',
    'Ever-evolving',
    'Daunting',
    'Cutting-edge',
    'Robust',
    'Power',
    'Bustling',
    'Metropolis',
    'Crucial',
    'Essential',
    'Vital',
    'Keen',
    'Fancy',
    'Labyrinth',
    'Gossamer',
    'Enigma',
    'Indelible',
    'Firstly',
    'Specifically',
    'Generally',
    'Importantly',
    'Similarly',
    'Nonetheless',
    'As a result',
    'Alternatively',
    'As well as',
    'Despite',
    'Essentially',
    'While',
    'Unless',
    'Also',
    'Even though',
    'Because',
    'In contrast',
    'Although',
    'In order to',
    'Due to',
    'Even if',
    'Given that',
    'Arguably',
    'To consider',
    'Ensure',
    'Out of the box',
    'Underscores',
    'Landscape',
    'Soul',
    'Crucible',
    'It depends on',
    'That being said',
    'You may want to',
    'This is not an exhaustive list',
    'In summary',
    'On the other hand',
    'To summarize',
    'Ultimately',
    'Pesky',
    "In today's digital era",
    'Enable',
    'Hustle and bustle',
    'Folks',
    'Sure',
    'Labyrinthine',
    'Moist',
    'Remnant',
    'As a professional',
    'Game changer',
    'Symphony',
    'Sights unseen',
    'Sounds unheard',
    'Dance',
    'Metamorphosis',
    'Leading edge',
    'Bleeding edge',
    'On the horizon',
    'Paradigm shift',
    'Seamless integration',
    'Innovative solutions',
    'Disruptive technology',
    'AI-powered',
    'Future-proof',
    'Next-gen',
    'User-friendly',
    'State-of-the-art',
    'Transformative',
    'Digital transformation',
    'In real-time',
    'Best-in-class',
    'Robust infrastructure',
    'High-impact',
    'Scalability',
    'End-to-end',
    'Leverage',
    'Synergy',
    'Quick wins',
    'Low-hanging fruit',
    'Move the needle',
    'Big data',
    'Data-driven',
    'Out-of-the-box thinking',
    'Onboarding',
    'Deliverables',
    'Touch base',
    'Reach out',
    'Take it to the next level',
    'Run it up the flagpole',
    'Drill down',
    'Circle back',
    'Deep dive',
    'Pivot',
    'Agile',
    'Scrum',
    'Holistic approach',
    'Quick and easy',
    'At the end of the day',
    'Bottom line',
    'Core competency',
    'Value proposition',
    'Mission-critical',
    'Win-win',
    'Pain points',
    'Best practices',
    'Customer-centric',
    'Cross-functional',
    'Benchmark',
    'Value-add',
    'Strategic alignment',
    'Thought leader',
    'Disruptive innovation',
    'Blue-sky thinking',
    'Greenfield',
    'Gray area',
    'Moving forward',
    'Make a difference',
    'One-stop shop',
    'User journey',
    'Customer journey',
    'Target audience',
    'Key takeaway',
    'User experience',
    'Seamless experience',
    'Personalized experience',
    'Customer feedback',
    'Customer engagement',
    'Stakeholder engagement',
    'Key stakeholders',
    'Leverage resources',
    'Streamline processes',
    'Continuous improvement',
    'Performance metrics',
    'Key performance indicators',
    'Smart goals',
    'Goal setting',
    'Results-oriented',
    'Outcome-focused',
    'Data insights',
    'Actionable insights',
    'Predictive analytics',
    'Prescriptive analytics',
    'Descriptive analytics',
    'Data analytics',
    'Insightful',
    'Key insights',
    'Analytics-driven',
    'Proactive approach',
    'Reactive approach',
    'Real-time data',
    'Data visualization',
    'Data storytelling',
    'Storytelling',
    'Narrative',
    'Content strategy',
    'Content marketing',
    'Content creation',
    'Engaging content',
    'Viral content',
    'Content curation',
    'Digital content',
    'Branded content',
    'Marketing campaign',
    'Digital marketing',
    'Online marketing',
    'Social media marketing',
    'Marketing strategy',
    'Growth hacking',
    'Customer acquisition',
    'Customer retention',
    'Customer loyalty',
    'Customer satisfaction',
    'Customer support',
    'Customer success',
    'Product roadmap',
    'Product lifecycle',
    'Product development',
    'Product management',
    'Product innovation',
    'Innovative product',
    'New product',
    'Product launch',
    'Market research',
    'Competitive analysis',
    'SWOT analysis',
    'Brand awareness',
    'Brand loyalty',
    'Brand equity',
    'Brand recognition',
    'Brand positioning',
    'Brand strategy',
    'Brand voice',
    'Brand messaging',
    'Visual identity',
    'Corporate identity',
    'Brand guidelines',
    'Rebranding',
    'Brand refresh',
    'Brand consistency',
    'Brand differentiation',
    'Brand promise',
    'Customer persona',
    'Target market',
    'Market segmentation',
    'Niche market',
    'Competitive advantage',
    'Value chain',
    'Customer value',
    'Brand advocate',
    'Brand ambassador',
    'Thought leadership',
    'Market trends',
    'Industry trends',
    'Trend analysis',
    'Market dynamics',
    'Consumer behavior',
    'Buying behavior',
    'Purchase decision',
    'Sales funnel',
    'Conversion funnel',
    'Lead generation',
    'Lead nurturing',
    'Sales cycle',
    'Sales pipeline',
    'Sales strategy',
    'Sales tactics',
    'Sales enablement',
    'Account management',
    'Key accounts',
    'Business development',
    'Strategic partnerships',
    'Partner ecosystem',
    'Channel strategy',
    'Distribution channel',
    'Sales forecast',
    'Revenue growth',
    'Revenue stream',
    'Profit margins',
    'Cost structure',
    'Financial performance',
    'Return on investment',
    'Cost-benefit analysis',
    'Break-even analysis',
    'Financial metrics',
    'Financial projections',
    'Cash flow',
    'Profit and loss',
    'Balance sheet',
    'Budgeting',
    'Financial planning',
    'Risk management',
    'Risk assessment',
    'Risk mitigation',
    'Business continuity',
    'Contingency planning',
    'Crisis management',
    'Corporate governance',
    'Compliance',
    'Regulatory compliance',
    'Ethical standards',
    'Corporate responsibility',
    'Sustainability',
    'Environmental impact',
    'Social impact',
    'Corporate citizenship',
    'Corporate culture',
    'Employee engagement',
    'Talent management',
    'Workforce development',
    'Employee retention',
    'Employee satisfaction',
    'Workplace culture',
    'Diversity and inclusion',
    'Human capital',
    'Leadership development',
    'Management training',
    'Professional development',
    'Performance appraisal',
    'Performance management',
    'Succession planning',
    'Organizational development',
    'Change management',
    'Organizational effectiveness',
    'Strategic planning',
    'Strategic goals',
    'Business strategy',
    'Operational strategy',
    'Competitive strategy',
    'Growth strategy',
    'Digital strategy',
    'Innovation strategy',
    'Technology strategy',
    'IT strategy',
    'Cybersecurity',
    'Data privacy',
    'Information security',
    'IT governance',
    'Technology adoption',
    'Emerging technologies',
    'Artificial intelligence',
    'Machine learning',
    'Internet of Things',
    'Blockchain',
    'Data science',
    'Data management',
    'Cloud computing',
    'Cloud infrastructure',
    'Software as a Service',
    'Platform as a Service',
    'Infrastructure as a Service',
    'IT services',
    'Managed services',
    'IT support',
    'IT operations',
    'IT infrastructure',
    'Network security',
    'Cyber threat',
    'Cyber attack',
    'Data breach',
    'Incident response',
    'Business intelligence',
    'Data warehousing',
    'Data mining',
    'Analytics',
    'Predictive modeling',
    'Business analytics',
    'Data governance',
    'Data quality',
    'Data integration',
  ];

  // Create case-insensitive regex pattern for clichés
  const escapedPhrases = clichePhrases.map((phrase) => phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const clichePattern = new RegExp(`\\b(${escapedPhrases.join('|')})\\b`, 'gi');
  const clicheCount = countMatches(text, clichePattern);

  // Contraction usage
  const contractionPattern = /\b\w+'(t|s|re|ve|d|ll)\b/g;
  const contractionCount = countMatches(text, contractionPattern);
  const contractionRatio = words.length > 0 ? contractionCount / words.length : 0;

  return {
    ...unicodePatterns,
    burstiness: burstiness,
    high_repeats: highRepeats,
    cliche_count: clicheCount,
    contraction_ratio: contractionRatio,
  };
}

/**
 * Build AI detection prompt messages
 * @param {string} text - The text to analyze
 * @returns {Array} Array of message objects for AI detection
 */
function buildAiDetectionPrompt(text) {
  const metrics = extractAiSignals(text);
  const truncatedText = text.length > 300 ? text.substring(0, 300) + '...' : text;

  const systemPrompt =
    'You are an AI text detector. Output ONLY an integer from 0 to 100. No words. No punctuation. ' +
    'Consider both text and numeric signals: more em dashes, low burstiness, high n-gram repeats, ' +
    'few contractions, many clichés, special unicode → higher score. ' +
    '0=very human, 100=very AI.';

  const userPrompt =
    `Text:\n${truncatedText}\n\n` +
    `Metrics:\n${JSON.stringify(metrics, null, 2)}\n\n` +
    'Detection cues: More em dashes, low burstiness, high n-gram repeats, ' +
    'few contractions, many clichés, and special unicode artifacts increase the AI score. ' +
    'High burstiness, mixed sentence lengths, personal details, and informal tone decrease the AI score.\n\n' +
    'Return ONLY an integer between 0 and 100. No words, no punctuation, no explanations.\n' +
    '0 = definitely human, 100 = definitely AI.\n' +
    'Score:';

  return [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];
}

// Export for Next.js
export { extractAiSignals, buildAiDetectionPrompt };
